### ISSUE TITLE
Issue with new deployement

### ISSUE THREAD

**Issue by kaczmar1243** [fleetbase/fleetbase#312]
Hello guys!

I currently trying to deploy application for 1st time.
I like to deploy things directly on OS but I had problem with NPM package:
`npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful`

I decided to try docker instead but I struggle with deployment as well.
So after pulling everything looks fine:
![image](https://github.com/user-attachments/assets/e92fc051-6ec0-4936-a092-de972933866c)

But when I go inside machine and trying `sh deploy.sh` i have below issue:
![image](https://github.com/user-attachments/assets/3c351638-1b81-4807-b3d3-5ec930e9d654)

I did literraly no changes in docker-compose.yml file, just pulled and did commands that were in instruction.

**Comment by roncodes** [comment]
See https://laravel.com/docs/11.x/encryption#configuration

**Comment by roncodes** [comment]
Also don't use npm, the package manager is pnpm

**Comment by kaczmar1243** [comment]
@roncodes You tell I should use pnmp instead of npm?
![image](https://github.com/user-attachments/assets/37c5eea7-9ddc-4011-8979-e70eb17b2ce0)

**Comment by kaczmar1243** [comment]
Anyway I feels like I am too dumb to walk through docker/standalone instruction.

I am trying to deal with configuration but in my opinion instruction to deploy this application is missing something or something is not written well.(And I don't blame you :) )
I tried to create .env in /api
![image](https://github.com/user-attachments/assets/fa614c1b-1489-4b00-ac81-013d57e340cb)
I tried to create .env file for docker-compose itself but no luck in both cases

**Comment by roncodes** [comment]
If you're doing standalone installation all you're doing is installing and configuring required services manually which each of these services have their own detailed install and config documentation. Then next you just setup and configure Fleetbase which is no more than a Laravel and Ember.js app. 

We recommend Docker because everything is already done with minor tweaks. 

As for the APP_KEY this is a Laravel dependency for encryption.  You can generate one online or through their CLI and just put it in the environment anyhow.
