### ISSUE TITLE
Cors Error

### ISSUE THREAD

**Issue by jeetenkumarsingh** [fleetbase/fleetbase#313]
Hi there,

I have successfully installed script with proper wss setup and it's working fine. But as per documentation I setup domain in config/cors.php and .env file for CONSOLE HOST, but still getting cors error after it. Sometimes it's login to console dashboard, sometimes cors error. I am using Debian Nginx environment. I appreciate your effort and help.

**Comment by roncodes** [comment]
Please read https://docs.fleetbase.io/getting-started/troubleshoot#cors-errors

**Comment by jeetenkumarsingh** [comment]
I have already followed documentation steps,  still cors error.

**Comment by roncodes** [comment]
If you're still having CORS error then you are not following the docs correctly. 

To help further you'll need to post logs from your browser console and browser network logs.

And or logs from docker. Or any error at all.

**Comment by jeetenkumarsingh** [comment]
I tried to install from source. All is set as in documentation of Install from Source. Cors setting also done. First it login very smoothly. But after visiting inner pages, it starts with cors error between console and api. It's weired behavior of not maintaining cors session properly. Please check and guide , if anything I can configure at Nginx and Laravel API end.

**Comment by roncodes** [comment]
CORS is not session based, it's a web browser security standard. https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

If login works, but after you get CORS error this indicates that one service is not setup correctly (which is most likely redis) - causing an error in the response (500) which would not contain the correct headers for the browser.

I recommend using Docker, otherwise refer or consult to the individual services documentation and guides to make sure they are installed and configured correctly.
